### ISSUE TITLE
[Feedback]: ABI

### ISSUE THREAD

**Issue by Mukumays** [matter-labs/zksync-docs#263] opened 2024-11-20 18:31 UTC
### Description

[{"inputs":[{"internalType":"address","name":"logic","type":"address"},{"internalType":"address","name":"admin","type":"address"},{"internalType":"bytes","name":"_data","type":"bytes"}],"stateMutability":"payable","type":"constructor"},{"anonymous":false,"inputs":[{"indexed":false,"internalType":"address","name":"previousAdmin","type":"address"},{"indexed":false,"internalType":"address","name":"newAdmin","type":"address"}],"name":"AdminChanged","type":"event"},{"anonymous":false,"inputs":[{"indexed":true,"internalType":"address","name":"beacon","type":"address"}],"name":"BeaconUpgraded","type":"event"},{"anonymous":false,"inputs":[{"indexed":true,"internalType":"address","name":"implementation","type":"address"}],"name":"Upgraded","type":"event"},{"stateMutability":"payable","type":"fallback"},{"stateMutability":"payable","type":"receive"}]

But this contract also has neither this requestL2Transaction nor any other function in the ABI requestL2TransactionTwoBridges

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MexicanAce** [comment] 2024-11-21 08:00
Duplicate of #262

**Closed as not planned by MexicanAce** 2024-11-21 08:00 UTC
Labels: duplicate, triage, feedback
